/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-OTP.h
 #	source generated by 4D Plugin Wizard
 #	Project : OTP
 #	author : miyako
 #	2024/02/21
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_OTP_H
#define PLUGIN_OTP_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#include "base32.h"

#include <openssl/evp.h>
#include <openssl/hmac.h>

#if defined(_WIN32)
#    include <sysinfoapi.h>
#else
#    include <sys/time.h>
#endif

#pragma mark -

void OTP_Generate(PA_PluginParameters params);

static const int32_t SHA1_BYTES   = 160 / 8;    // 20
static const int32_t SHA256_BYTES = 256 / 8;    // 32
static const int32_t SHA512_BYTES = 512 / 8;    // 64

static int hmac_algo_sha1(const char* byte_secret, const char* byte_string, char* out);
static int hmac_algo_sha256(const char* byte_secret, const char* byte_string, char* out);
static int hmac_algo_sha512(const char* byte_secret, const char* byte_string, char* out);
static uint64_t get_current_time();

#endif /* PLUGIN_OTP_H */
